### PR TITLE
use 'supports?' feature for assume role field

### PR DESCRIPTION
**Pull request by AlexanderZagaynov**
This is a follow-up for https://github.com/ManageIQ/manageiq-providers-amazon/pull/538 as demanded by UI team (https://github.com/ManageIQ/manageiq-ui-classic/pull/5621).

### CODE REVIEW

**Comment by AlexanderZagaynov** [comment]
@agrare please review

**Comment by djberg96** [comment]
The test failure looks unrelated, can you restart it?

**Comment by agrare** [comment]
@djberg96 test failure is due to dependency on https://github.com/ManageIQ/manageiq/pull/19088

**Comment by AlexanderZagaynov** [comment]
@djberg96 @agrare it's green

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 1099f43bb81a21cd0e874e31593a97eff87fcc9a
Author: Adam Grare <agrare@redhat.com>
Date:   Mon Aug 5 13:03:48 2019 -0400

    Merge pull request #550 from AlexanderZagaynov/features/sts_assume_role
    
    use 'supports?' feature for assume role field
    
    (cherry picked from commit a918fc4f36cdcb9534a0003e94685c1ef34a3f58)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1631845
```

**Pull request merged**
