### PR TITLE
Updated Codeclimate gem

### PR DESCRIPTION
**Pull request by juliancheal**
Fixes this issue https://github.com/codeclimate/ruby-test-reporter#upgrading-from-pre-10-versions

### CODE REVIEW

**Comment by Fryguy** [comment]
@juliancheal You also have to update https://github.com/ManageIQ/manageiq-providers-amazon/blob/1a30b2877cc76b7419a556eef80ec3e03519cdae/spec/spec_helper.rb#L1-L4 as per the documentation on that link

**Comment by Fryguy** [comment]
Also, you need to update the .travis.yml to send the new results, probably in an after_script step.

**Comment by juliancheal** [comment]
Pfft who reads documentation. But seriously I'm not sure which bit in the docs you're referring to :(

**Comment by Fryguy** [comment]
Oh, it's a little further up in the doc in the Installation section: https://github.com/codeclimate/ruby-test-reporter#installation, but that doesn't describe it very well.  Maybe I'll make a PR to ruby-test-reporter to clarify the documentation.

- Bullet 1 is this PR, so that's good
- Bullet 2 suggests starting simplecov, so you need to replace https://github.com/ManageIQ/manageiq-providers-amazon/blob/1a30b2877cc76b7419a556eef80ec3e03519cdae/spec/spec_helper.rb#L1-L4  with

    ```ruby
    require 'simplecov'
    SimpleCov.start
    ```
- Bullet 3 is the same as existing, so no change there
- Bullet 4 requires a change to the .travis.yml  I think you can just add the following after the `script:` section:

    ```yaml
    after_script: bundle exec codeclimate-test-reporter
    ```

**Comment by juliancheal** [comment]
Specs failed, but I might not have had the newest version of the amazon codebase. So rebased and repushed.

**Comment by Fryguy** [comment]
Merging anyway, since the changes are correct, and something else is broken.

**Comment by juliancheal** [comment]
👍 to living on the edge.

**Pull request merged**
