### PR TITLE
remove descendant loader config

### PR DESCRIPTION
**Pull request by durandom**
no need for adding this since this is in manageiq
https://github.com/ManageIQ/manageiq/pull/12221/commits/83300fbfa871afc08343daeb959299b9a52e4887

### CODE REVIEW

**Comment by durandom** [comment]
cc @juliancheal for lenvo

**Comment by durandom** [comment]
@blomquisg please merge if ok

**Comment by blomquisg** [comment]
@durandom hrm, I don't see this in the core MIQ repo.  How is this obviated by the core repo?

**Comment by durandom** [comment]
>  I don't see this in the core MIQ repo. 

See ManageIQ/manageiq@83300fb 
There we register all Rails Engines that are namespaced under `ManageIQ::Providers` as `Vmdb::Plugins` and [here](https://github.com/ManageIQ/manageiq/commit/83300fb#diff-2dffee21730102d591f668045fe85db7R15) we add `/app` to the path

**Pull request merged**
