### PR TITLE
Moving to use only kwargs for InventoryCollection init

### PR DESCRIPTION
**Pull request by Ladas**
Moving to use only kwargs for InventoryCollection init.
Unifying format, preparing for the abstraction of the
InventoryCollection definitions.

Depends on https://github.com/ManageIQ/manageiq/pull/13739

### CODE REVIEW

**Comment by Ladas** [comment]
I will send rubocop -a for the whole manager_refresh as a next PR, once @durandom has his enhancements merged

**Comment by durandom** [comment]
makes master green again

**Comment by chrisarcand** [comment]
Minor note (not trying to be pedantic, I was actually genuinely confused for a bit):

These aren't keyword arguments :)

**Comment by durandom** [comment]
@chrisarcand I like how pedantic people always start sentences with *not trying to be...* 😛 
But you have a point, and I also [pointed that out](https://github.com/ManageIQ/manageiq/pull/13743#pullrequestreview-21244757).
But those hashes are later used to fill keyword args https://github.com/ManageIQ/manageiq/pull/13739/files#diff-fb299216c1dbe0f44b0f5c2352b4b6e5R12

If there is still a subtle difference, please continue to be pedantic :)

**Comment by Ladas** [comment]
It acts like kwargs, that is enough for me :-D

**Comment by chrisarcand** [comment]
❤️

**Pull request merged**
