### PR TITLE
Added supports_provisioning?  support for Amazon Template

### PR DESCRIPTION
**Pull request by h-kataria**
Changes to address https://github.com/ManageIQ/manageiq/pull/10561#discussion_r75485697

https://bugzilla.redhat.com/show_bug.cgi?id=1344079
https://bugzilla.redhat.com/show_bug.cgi?id=1347278

@durandom, please review, these are changes to support Template provisioning in Amazon, related to changes in https://github.com/ManageIQ/manageiq/pull/10651

### CODE REVIEW

**Comment by durandom** [comment]
@h-kataria could you bring code in line with the latest version of https://github.com/ManageIQ/manageiq/pull/10651 - although we dont have a rubocop yet watching over us :smile:

**Comment by h-kataria** [comment]
@durandom this code is already in line with changes in https://github.com/ManageIQ/manageiq/pull/10651

**Comment by h-kataria** [comment]
@durandom @dclarizio can you please add label Darga/yes to this PR

**Comment by durandom** [comment]
darga PR is at https://github.com/ManageIQ/manageiq/pull/10746

**Comment by chessbyte** [comment]
Darga Backport details from https://github.com/ManageIQ/manageiq repo:
```sh
$ git remote add amazon git@github.com:ManageIQ/manageiq-providers-amazon

$ git fetch amazon

$ git cherry-pick -m 1 -x -Xsubtree=gems/manageiq-providers-amazon  777f9d7
[darga 51b7e20] Merge pull request #34 from h-kataria/template_supports_provsioning
 Author: Marcel Hild <hild@b4mad.net>
 Date: Tue Aug 23 16:13:19 2016 +0200
 1 file changed, 8 insertions(+)

$ git log
commit 51b7e20db37a958575c5e96ea56c835d1f774690
Author: Marcel Hild <hild@b4mad.net>
Date:   Tue Aug 23 16:13:19 2016 +0200

    Merge pull request #34 from h-kataria/template_supports_provsioning
    
    Added supports_provisioning?  support for Amazon Template
    (cherry picked from commit 777f9d7c612d6d9b6d0687925e3017ebc768340e)
```

**Pull request merged**
