### PR TITLE
removed gov cloud from list of regions

### PR DESCRIPTION
**Pull request by durandom**
addresses https://bugzilla.redhat.com/show_bug.cgi?id=1346065

### CODE REVIEW

**Comment by durandom** [comment]
darga pr is at https://github.com/ManageIQ/manageiq/pull/10902

**Comment by Fryguy** [comment]
Whoa...why did we remove this?

**Comment by chessbyte** [comment]
@blomquisg @Fryguy @durandom should we revert this PR?

**Comment by durandom** [comment]
@chessbyte yes, I think so. Can this be done via github buttons or do I have to do this via a PR?

**Comment by blomquisg** [comment]
@durandom I think it needs to be a separate PR

**Comment by durandom** [comment]
> I think it needs to be a separate PR

yes, will incorporate that into https://github.com/ManageIQ/manageiq-providers-amazon/issues/44

**Pull request merged**
