### PR TITLE
get virtualization_type and root_device_type from instance

### PR DESCRIPTION
**Pull request by durandom**
in case the image does not exist in miq, like we dont import
public images but the instance was started from a public image, which
can only happen if you start the instance outside of miq.
then before the hardware would still be added to the vm, but without
the `_type` fields mentioned above

BZ https://bugzilla.redhat.com/show_bug.cgi?id=1378039

### CODE REVIEW

**Comment by durandom** [comment]
@Ladas can you have a look ?

**Comment by mkanoor** [comment]
@durandom 
Can we have a spec for this?

**Comment by Ladas** [comment]
@durandom the specs are already there, we could just add check for root_device_type here
https://github.com/Ladas/manageiq-providers-amazon/blob/75709218671474cc8c2c2165a30a45b52e3d6869/spec/models/manageiq/providers/amazon/cloud_manager/refresher_spec.rb#L393-L393

**Comment by durandom** [comment]
@mkanoor we already check in the spec for `root_device_type` and `virtualization_type` present for some templates. So, I think this should be good.

@blomquisg can you merge this?

**Comment by mkanoor** [comment]
@blomquisg 
Can you please update this, we have a bugzilla pending on this

**Comment by durandom** [comment]
@chessbyte https://bugzilla.redhat.com/show_bug.cgi?id=1379697 wants this in darga too

can you cherry pick that with the `Xsubtree` trick or should I open an PR?

**Comment by chessbyte** [comment]
Euwe Backport details:
```sh
$ git log
commit a5ae8e5b43b8a2f3600ce60cd9a60a0d32f1eaa1
Author: Greg Blomquist <blomquisg@gmail.com>
Date:   Mon Oct 10 14:19:53 2016 -0400

    Merge pull request #51 from durandom/refresh_parser_hardware
    
    get virtualization_type and root_device_type from instance
    (cherry picked from commit bf1b8b9136865b472b098f0c05df01e2157a2147)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1384211
```

**Comment by blomquisg** [comment]
> can you cherry pick that with the Xsubtree trick or should I open an PR?

@durandom can you open a separate `[DARGA]` specific PR on the MIQ repo?

**Comment by chessbyte** [comment]
Darga Backport details (to manageiq repo):
```sh
$ git cherry-pick -e -x -m 1 -Xsubtree=gems/manageiq-providers-amazon  bf1b8b9  
[darga e091e4e] Merge pull request #51 from durandom/refresh_parser_hardware
 Author: Greg Blomquist <blomquisg@gmail.com>
 Date: Mon Oct 10 14:19:53 2016 -0400
 1 file changed, 3 insertions(+), 8 deletions(-)

$ git log -1
commit e091e4ed0c8b5e7fc4f2c4d537d5898549451921
Author: Greg Blomquist <blomquisg@gmail.com>
Date:   Mon Oct 10 14:19:53 2016 -0400

    Merge pull request #51 from durandom/refresh_parser_hardware
    
    get virtualization_type and root_device_type from instance
    (cherry picked from commit bf1b8b9136865b472b098f0c05df01e2157a2147)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1379697
```

**Comment by chessbyte** [comment]
@durandom @blomquisg took care of it myself

**Comment by durandom** [comment]
@chessbyte awesome, thanks a lot :clap:

**Pull request merged**
