### PR TITLE
[WIP] Added China (Beijing) cn-north-1 region.

### PR DESCRIPTION
**Pull request by juliancheal**
Fixes issue #294 BZ https://bugzilla.redhat.com/show_bug.cgi?id=1500613

### CODE REVIEW

**Comment by juliancheal** [comment]
I don't think we have a way to test this, unless we are in China :/

**Comment by juliancheal** [comment]
@miq-bot assign @bronaghs

**Comment by bronaghs** [comment]
I think we should make this a WIP while we wait for credentials to a China region to test.

**Comment by Fryguy** [comment]
Merged #436 which generlized this.

**Pull request closed without merging**
