### PR TITLE
refactor validate_reboot_guest to supports :reboot_guest

### PR DESCRIPTION
**Pull request by durandom**
continue work done in https://github.com/ManageIQ/manageiq/pull/11075 here

makes CI :green_heart: again

### CODE REVIEW

**Comment by durandom** [comment]
@Fryguy  @chessbyte we need this in the euwe branch here too, now that https://github.com/ManageIQ/manageiq/pull/11075 has been backported after all.

How should we handle this?
How about the same labeling approach as in ManageIQ, but I'll do the backporting to relieve @chessbyte

**Comment by Fryguy** [comment]
@durandom I agree...I'll make the euwe labels.

**Comment by chessbyte** [comment]
If we have an `euwe` branch in this repo, I will backport.

**Comment by chessbyte** [comment]
Euwe Backport details:
```sh
$ git log
commit 3d6ec32bddc979fe36cec44f1b3b8abb09da094e
Author: Greg Blomquist <blomquisg@gmail.com>
Date:   Tue Oct 4 10:19:10 2016 -0400

    Merge pull request #53 from durandom/supports_rebooot_guest
    
    refactor validate_reboot_guest to supports :reboot_guest
    (cherry picked from commit c86fa98cdfc3d65458338fbe3df1deaf81101715)
```

**Pull request merged**
