### PR TITLE
fix types count

### PR DESCRIPTION
**Pull request by AlexanderZagaynov**
Fix for https://github.com/ManageIQ/manageiq-providers-amazon/pull/554#issuecomment-527903227

### CODE REVIEW

**Comment by AlexanderZagaynov** [comment]
@miq-bot add_label ivanchuk/yes

**Comment by AlexanderZagaynov** [comment]
@agrare please review

**Comment by agrare** [comment]
@AlexanderZagaynov I think you'll need to create an ivanchuk specific branch, since this fails CI on master.

I assume this is the flavor that is missing on ivanchuk (https://github.com/ManageIQ/manageiq-providers-amazon/pull/552) @simaishi an alternative is to backport that PR

**Comment by AlexanderZagaynov** [comment]
@agrare PR you mention is about regions, not flavour. Probably something else is missing?

**Comment by agrare** [comment]
:man_facepalming: yeah you're right, but yeah still the question of is the count right or is a flavor missing is valid

**Comment by AlexanderZagaynov** [comment]
closing in favour of https://github.com/ManageIQ/manageiq-providers-amazon/pull/556

**Pull request closed without merging**
