### PR TITLE
Add in missing user creation audit event.

### PR DESCRIPTION
**Pull request by juliancheal**
Recieved from this PR https://github.com/ManageIQ/manageiq/pull/17852

### CODE REVIEW

**Comment by juliancheal** [comment]
@agrare tests are passing locally, but I'm not sure where `userNameType ` in the message
```
message => "User creation successful for User: userNameType with ID: #{username}"
```

is coming from :(

**Comment by agrare** [comment]
@juliancheal looks like it is coming from here
```
   83:     def update_user_attributes(user, username, amazon_user)
=> 84:       user.userid = username
   85:       user.name   = amazon_user.name
   86:     end
   87: 
   88:     private
(byebug) amazon_user
#<Aws::IAM::User name="userNameType">
```

**Comment by agrare** [comment]
I think we can improve the stubbed user to give it a better username, merging this for now to get the repo back to green.

**Comment by juliancheal** [comment]
@agrare ah are we getting that from the user stubbing? I see, that explains why I hadn't seen it I was testing the original PR with actual amazon log in.

**Pull request merged**
