### PR TITLE
Ensure user_data is Base64 encoded

### PR DESCRIPTION
**Pull request by bdunne**
This PR and https://github.com/ManageIQ/manageiq/pull/9800 are co-dependent, we can re-run the tests once 9800 is merged to get the tests passing.

https://bugzilla.redhat.com/show_bug.cgi?id=1355895

### CODE REVIEW

**Comment by bdunne** [comment]
Reopened to kick Travis
@Fryguy @gmcculloug Please review

**Comment by gmcculloug** [comment]
👍  @Fryguy I do not have merge rights on this repo so will need you or someone with access to merge.

**Comment by Fryguy** [comment]
@bdunne Is this darga/yes or no

**Comment by bdunne** [comment]
@Fryguy darga/yes

**Pull request merged**
