### PR TITLE
Introduce Amazon S3 StorageManager

### PR DESCRIPTION
**Pull request by aiperon**
Similarly to #101 this commit sets up the core structure of the new AWS S3 manager. 
It provides just the basic stubs and tests that are to be extended.

The refresher collects data about existing buckets.

@miq-bot add_label enhancement

### CODE REVIEW

**Comment by Ladas** [comment]
@aiperon ok, I think first we will merge https://github.com/ManageIQ/manageiq-providers-amazon/pull/101

this one will probably conflict then. Could you fix the rubocop warnings with Style... in the meantime?

**Comment by Ladas** [comment]
@aiperon could you rebase and follow what was done in? https://github.com/ManageIQ/manageiq-providers-amazon/pull/101

You don't need to push the new version of a refresher and a parser in this PR though, it can come later. So just cleanup according to #101 and this is ready.

**Comment by aiperon** [comment]
I've rebased my branch, fixed style issues and followed recommendations for #101.

**Comment by aiperon** [comment]
@miq-bot add_label wip

**Comment by aiperon** [comment]
Added new version of a refresher and a parser.
Renamed from
`ManageIQ::Providers::Amazon::ObjectStorageManager < ManageIQ::Providers::StorageManager`
to
`ManageIQ::Providers::Amazon::StorageManager::EBS < ManageIQ::Providers::StorageManager`.

**Comment by Ladas** [comment]
@aiperon ah, I think rename caused you need to rebase again :-)

**Comment by aiperon** [comment]
@Ladas fortunately it's not a big deal in that case. Done & green.

**Comment by Ladas** [comment]
@aiperon looks great, thank you for the contribution :-)

**Pull request merged**
