### PR TITLE
Added instance update event handling

### PR DESCRIPTION
**Pull request by juliancheal**
Fixes BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1537520

### CODE REVIEW

**Comment by juliancheal** [comment]
@miq-bot add_label bug, gaprindashvili/yes

**Comment by bronaghs** [comment]
@juliancheal - so this PR will change the event category from an "addition" to an "update". However, the BZ states that the event is not coming in at all so no refresh is kicked off and the new name is not reflected in the DB.

**Comment by bronaghs** [comment]
@juliancheal - Bump

**Comment by juliancheal** [comment]
Made a comment on the BZ.

**Comment by juliancheal** [comment]
Changing the name of a VM in EC2, creates a `AWS_API_CALL_CreateTags` event.
With a `message`

```
request: {"resourcesSet"=>{"items"=>[{"resourceId"=>"i-0a67c549558c9c392"}]}, "tagSet"=>{"items"=>[{"key"=>"Name", "value"=>"julian_le_jaune"}]}}, response: {"_return"=>true}
```

**Comment by juliancheal** [comment]
Looking at the logs, when we change the VM name in the EC2 console, we instantly get a `AWS_API_CALL_CreateTags` event, but nothing appears in the Timeline for the VM.

This is the evm.log

```
INFO -- : MIQ(MiqEventHandler::Runner#get_message_via_drb) Message id: [1042], MiqWorker id: [70], Zone: [default], Role: [event], Server: [], Ident: [ems], Target id: [1], Instance id: [], Task id: [], Command: [EmsEvent.add], Timeout: [600], Priority: [100], State: [dequeue], Deliver On: [], Data: [], Args: [{:event_type=>"AWS_API_CALL_CreateTags", :source=>"AMAZON", :full_data=>{"version"=>"0", "id"=>"", "detail-type"=>"AWS API Call via CloudTrail", "source"=>"aws.ec2", "account"=>"", "time"=>"2018-03-12T15:05:33Z", "region"=>"us-east-1", "resources"=>[], "detail"=>{"eventVersion"=>"1.05", "userIdentity"=>{"type"=>"IAMUser", "principalId"=>"", "arn"=>"", "accountId"=>"", "accessKeyId"=>"", "userName"=>"", "sessionContext"=>{"attributes"=>{"mfaAuthenticated"=>"false", "creationDate"=>"2018-03-12T12:32:56Z"}}, "invokedBy"=>"signin.amazonaws.com"}, "eventTime"=>"2018-03-12T15:05:33Z", "eventSource"=>"ec2.amazonaws.com", "eventName"=>"CreateTags", "awsRegion"=>"us-east-1", "sourceIPAddress"=>"", "userAgent"=>"signin.amazonaws.com", "requestParameters"=>{"resourcesSet"=>{"items"=>[{"resourceId"=>"i-0a67c549558c9c392"}]}, "tagSet"=>{"items"=>[{"key"=>"Name", "value"=>"julian_le_noir"}]}}, "responseElements"=>{"_return"=>true}, "requestID"=>"99219248-50d9-4d23-ac2c-e159b66e8a1e", "eventID"=>"cbc3d514-da3c-458f-be87-abd7acc69712", "eventType"=>"AwsApiCall"}, "eventType"=>"AWS_API_CALL_CreateTags", "event_source"=>:cloud_watch_api, "messageId"=>"27746a53-b30c-428e-8623-5f18174dd3c9"}, :ems_id=>1, :message=>"request: {\"resourcesSet\"=>{\"items\"=>[{\"resourceId\"=>\"i-0a67c549558c9c392\"}]}, \"tagSet\"=>{\"items\"=>[{\"key\"=>\"Name\", \"value\"=>\"julian_le_noir\"}]}}, response: {\"_return\"=>true}", :timestamp=>"2018-03-12T15:05:33Z", :vm_ems_ref=>nil, :availability_zone_ems_ref=>nil}], Dequeued in: [4.014413] seconds
```

**Comment by juliancheal** [comment]
Not sure why Travis is failing, All tests are passing for me locally.

`526 examples, 0 failures`

**Comment by juliancheal** [comment]
@agrare any idea on why the tests are failing? They pass locally, and I've rebased to the latest version.

**Comment by agrare** [comment]
@juliancheal looks like no one fixed the amazon repo after https://github.com/ManageIQ/manageiq/pull/17021 was merged, see some of the PRs linked from there there like https://github.com/ManageIQ/manageiq-providers-ovirt/pull/222

**Comment by bronaghs** [comment]
@juliancheal - Would be bonus to call a target refresh of the VM after the name is changed, instead of a full refresh of the provider. Can you make a separate PR to do that? Thanks.

**Comment by agrare** [comment]
Make sure to backport https://github.com/ManageIQ/manageiq/pull/17160 with this change.

**Comment by himdel** [comment]
This PR break ui-classic travis...

`EmsEvent.event_groups` returns a hash where the value needs to have a `:name` and `:detail`.

Before this PR, key `:addtion` had the value of 

```
{:critical=>
  ["CloneTaskEvent",
   "ClusterCreatedEvent",
   "CreateFolder",
   "DatacenterCreatedEvent",
   "DatastoreDiscoveredEvent",
   "HostConnectedEvent",
   "HOST_DETECTED",
   "HOST_REGISTER_AUTO_APPROVE_PATTERN",
   "HOST_REGISTER_ERROR_UPDATING_HOST",
   "HOST_REGISTER_ERROR_UPDATING_HOST_ALL_TAKEN",
   "HOST_REGISTER_ERROR_UPDATING_NAME",
   "HOST_REGISTER_ERROR_UPDATING_NAMES_ALL_TAKEN",
   "HOST_REGISTER_EXISTING_HOST_UPDATE_FAILED",
   "HOST_REGISTER_FAILED",
   "HOST_REGISTER_HOST_IS_ACTIVE",
   "HOST_REGISTER_NAME_IS_ACTIVE",
   "HOST_REGISTER_SUCCEEDED",
   "IMPORTEXPORT_STARTING_EXPORT_TEMPLATE",
   "IMPORTEXPORT_EXPORT_TEMPLATE",
   "ResourcePoolCreatedEvent",
   "TemplateDeployedEvent",
   "USER_ADD",
   "USER_ADD_HOST",
   "USER_ADD_VM",
   "USER_ADD_VM_FINISHED_FAILURE",
   "USER_ADD_VM_FINISHED_SUCCESS",
   "USER_ADD_VM_TEMPLATE",
   "USER_ADD_VM_TEMPLATE_FINISHED_FAILURE",
   "USER_ADD_VM_TEMPLATE_FINISHED_SUCCESS",
   "USER_FAILED_ADD_HOST",
   "USER_FAILED_ADD_VM_TEMPLATE",
   "GceOperationDone_compute.instances.insert",
   "VmConnectedEvent",
   "VmCreatedEvent",
   "VmDeployedEvent",
   "VmRegisteredEvent",
   "AWS_EC2_Instance_CREATE",
   "AWS_API_CALL_RunInstances",
   "AWS_API_CALL_CreateTags",
   "AWS_EC2_Instance_UPDATE",
   "virtualMachines_write_EndRequest",
   "CONTAINER_CREATED",
   "REPLICATOR_SUCCESSFULCREATE",
   "REPLICATOR_FAILEDCREATE",
   "aggregate.addhost.end",
   "aggregate.create.end",
   "aggregate.removehost.end",
   "aggregate.updateprop.end",
   "aggregate.updatemetadata.end",
   "identity.project.created",
   "identity.project.deleted",
   "identity.project.updated",
   "image.update",
   "image.create",
   "image.upload",
   "orchestration.stack.create.end",
   "orchestration.stack.create.error",
   "servergroup.create"],
 :detail=>
  ["CloneVM_Task",
   "CloneVM_Task_Complete",
   "CreateClusterEx",
   "CreateClusterEx_Complete",
   "CreateDatacenter",
   "CreateDatacenter_Complete",
   "CreateResourcePool",
   "CreateResourcePool_Complete",
   "CreateVM_Task",
   "CreateVM_Task_Complete",
   "ReconnectHost_Task",
   "RegisterVM_Task",
   "RegisterVM_Task_Complete",
   "VmBeingClonedEvent",
   "VmBeingCreatedEvent",
   "VmBeingDeployedEvent"],
 :name=>"Creation/Addition"}
```

which works :).

With this PR, there's a new key - `:update` but the value is just 

`{:critical=>["AWS_EC2_Instance_UPDATE"]}`

which crashes.


---

Failure on travis: https://gist.github.com/himdel/88694a73d3cd7dd0fc772660a69cde1d

**Comment by himdel** [comment]
@juliancheal Looks like the rest of the definition needs to live in `manageiq/config/settings.yml`.

Right now, the only valid keys are:

```
:addition:
:configuration:
:console:
:deletion:
:general:
:import_export:
:migration:
:network:
:power:
:snapshot:
:status:
:storage:
```

**Comment by bronaghs** [comment]
@simaishi - Another PR that needs to be backported with this:
ManageIQ/manageiq#17164

**Comment by juliancheal** [comment]
@miq-bot add_label fine/yes

/cc @simaishi ManageIQ/manageiq#17164 needs to be backported too

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 764748830f5f8829de5f7f39451619865131f834
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Thu Mar 15 09:45:49 2018 -0400

    Merge pull request #415 from juliancheal/missing_update_events
    
    Added instance update event handling
    (cherry picked from commit 77c2e877539ea8f44f09839a8980ddb5808db79d)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1558594
```

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 7c64927848dc84254b3a21dc7c48474174b6db91
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Thu Mar 15 09:45:49 2018 -0400

    Merge pull request #415 from juliancheal/missing_update_events
    
    Added instance update event handling
    (cherry picked from commit 77c2e877539ea8f44f09839a8980ddb5808db79d)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1558595
```

**Pull request merged**
