### PR TITLE
[wip] EmsNetwork controller specs

### PR DESCRIPTION
**Pull request by Ladas**
EmsNetwork controller specs

### CODE REVIEW

**Comment by durandom** [comment]
https://github.com/ManageIQ/manageiq-providers-amazon/pull/32 is merged. please rebase and the tests should be failing

**Comment by Ladas** [comment]
@durandom hm ,we might need to add some javascript libraries, so we can have tests that render something?

 couldn't find file 'es6-shim' with type 'application/javascript'

**Comment by durandom** [comment]
But we run the specs inside manageiq as a dummy app.
Does it work locally for you?

Have a look at https://github.com/ManageIQ/manageiq-providers-amazon/pull/32
You can also run the tests from manageiq, does it work then?

**Comment by Ladas** [comment]
@durandom yes, it works from ManageIQ, not sure what we are missing, maybe we need to add the javacript libs in some special way?

**Comment by Ladas** [comment]
@Fryguy hello, would you know what do we miss in the CI setup, that we get Failure/Error: //= require es6-shim ?

**Comment by Fryguy** [comment]
It sounds like the bower install stuff from ManageIQ is not happening, but I'm not exactly sure why.

**Comment by Fryguy** [comment]
I wonder if this step is not sufficient: https://github.com/ManageIQ/manageiq-providers-amazon/blob/87bcab116e6b3a56ac5fb7862056715f84bf961d/bin/setup#L16-L28

From that it looks like it just does a bundle update, but I don't think it ever calls the bower install stuff.  @durandom I have to admit I don't understand the testing plumbing, so I'm not sure here.

**Comment by durandom** [comment]
bower not running is a good shot. I'll re-investigate this with https://github.com/ManageIQ/manageiq-providers-amazon/issues/6 in mind.

**Comment by Ladas** [comment]
@durandom we will need https://github.com/ManageIQ/manageiq/blob/master/.travis.yml#L25

**Pull request merged**
