### PR TITLE
added ability to disable regions at runtime

### PR DESCRIPTION
**Pull request by durandom**
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1346065

this needs settings.yml in gems to be merged first

### CODE REVIEW

**Comment by durandom** [comment]
Note, this should include a revert for this https://github.com/ManageIQ/manageiq-providers-amazon/pull/38

**Comment by durandom** [comment]
@blomquisg to make this green, https://github.com/ManageIQ/manageiq/pull/11912 has to be merged. Then kick CI here

**Comment by blomquisg** [comment]
I kicked CI after https://github.com/ManageIQ/manageiq/pull/11912 was merged, and still seeing failures.

**Comment by durandom** [comment]
@blomquisg yup, forgot to revert the removal of `us-gov` region. CI to the rescue :smile: 

now its green, merge?

**Comment by chessbyte** [comment]
Euwe Backport details:
```sh
$ git log -1
commit 7b742db1ed53c2e3267ea2530be35efa198afbfb
Author: Greg Blomquist <blomquisg@gmail.com>
Date:   Mon Oct 24 11:00:36 2016 -0400

    Merge pull request #44 from durandom/disable_regions
    
    added ability to disable regions at runtime
    (cherry picked from commit 38d897e288e5130722ccdd56f95112da353c29d2)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1346065
```

**Pull request merged**
