### PR TITLE
Prefer #first over [0] on an array

### PR DESCRIPTION
**Pull request by bdunne**

### CODE REVIEW

**Comment by bdunne** [comment]
@hsong-rh Please review

**Comment by juliancheal** [comment]
LGTM 👍

**Comment by bronaghs** [comment]
@bdunne - Apart from being easier on the eye, is there another benefit to this change? Just curious.

**Comment by bdunne** [comment]
That's all @bronaghs

**Comment by bronaghs** [comment]
@bdunne feel free to change my choice of labels

**Comment by bdunne** [comment]
For backport purposes... 
@miq-bot add_labels gaprindashvili/yes
@miq-bot rm_label gaprindashvili/no

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 9704c3c1496f11c06a85ff514f12d849a33a2d9e
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Mon Nov 6 14:26:16 2017 -0500

    Merge pull request #344 from bdunne/prefer_first
    
    Prefer #first over [0] on an array
    (cherry picked from commit e46a7cb7f4edc1e9257dfd23789f1f88065c9016)
```

**Pull request merged**
