### PR TITLE
new instance types

### PR DESCRIPTION
**Pull request by durandom**
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1427966

created via the new task in https://github.com/ManageIQ/manageiq-providers-amazon/pull/170

### CODE REVIEW

**Comment by durandom** [comment]
😱 spec number asserts strike again

**Comment by Ladas** [comment]
looks great, the minor changes of the flavor should not matter

**Comment by simaishi** [comment]
@durandom 3 of the spec files don't exist in Euwe.  Can you create an Euwe-specific PR (referencing this one) or suggest other PRs to backport.

**Comment by durandom** [comment]
@simaishi https://github.com/ManageIQ/manageiq-providers-amazon/pull/182 is a backport

**Comment by simaishi** [comment]
Backported to Euwe via https://github.com/ManageIQ/manageiq-providers-amazon/pull/182

**Pull request merged**
