### PR TITLE
Service dialog for orchestration template no longer contains tenant selection

### PR DESCRIPTION
**Pull request by bzwei**
https://bugzilla.redhat.com/show_bug.cgi?id=1642594

Fixes CI build failure caused by https://github.com/ManageIQ/manageiq/pull/18202

### CODE REVIEW

**Comment by JPrause** [comment]
@bzwei if this can be backported, please add the hammer/yes and gaprindashvili/yes labels

**Comment by JPrause** [comment]
@miq-bot add_label blocker

**Comment by bzwei** [comment]
@miq-bot add_label hammer/yes, gaprindashvili/yes

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 19d4fe2b2d7ee13501558b4b67d00e2cb1c852ff
Author: Adam Grare <agrare@redhat.com>
Date:   Mon Nov 19 11:56:07 2018 -0500

    Merge pull request #499 from bzwei/no_tenant
    
    Service dialog for orchestration template no longer contains tenant selection
    
    (cherry picked from commit 59c267d6fc76406fba0066eee7ee574456414693)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1642594
```

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit de56256ea252cba9263258cd722e69212e2e535e
Author: Adam Grare <agrare@redhat.com>
Date:   Mon Nov 19 11:56:07 2018 -0500

    Merge pull request #499 from bzwei/no_tenant
    
    Service dialog for orchestration template no longer contains tenant selection
    
    (cherry picked from commit 59c267d6fc76406fba0066eee7ee574456414693)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1651391
```

**Pull request merged**
