### PR TITLE
Move OrchestrationTemplateCfn to manageiq-providers-amazon

### PR DESCRIPTION
**Pull request by bzwei**
Prepare to move OrchestrationTemplate to each provider.

This is a step before the migration.

https://bugzilla.redhat.com/show_bug.cgi?id=1417021

### CODE REVIEW

**Comment by Ladas** [comment]
@bzwei seems like a valid CI failure. Does this depend on some core PR?

**Comment by bzwei** [comment]
@miq-bot add_label refactoring
@miq-bot assign @Ladas

**Comment by Ladas** [comment]
@bzwei can we fix the rubocop warning? Or you need to call the load there?

**Comment by bzwei** [comment]
@Ladas warning fixed.

**Pull request merged**
