### PR TITLE
Changelog 61

### PR DESCRIPTION
**Pull request by mfeifer**
3 PRS

[skip ci]

### CODE REVIEW

**Comment by mfeifer** [comment]
@miq-bot add_label wip

**Comment by mfeifer** [comment]
@miq-bot add_label documentation

**Comment by mfeifer** [comment]
@miq-bot remove_label wip

**Comment by bronaghs** [comment]
@mfeifer - Maybe this one too:
https://github.com/ManageIQ/manageiq-providers-amazon/pull/246

**Comment by mfeifer** [comment]
@bronaghs all set.  can you please merge?

**Pull request merged**
