### PR TITLE
new instance types

### PR DESCRIPTION
**Pull request by AlexanderZagaynov**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1724686

https://aws.amazon.com/blogs/aws/new-the-next-generation-i3en-of-i-o-optimized-ec2-instances/
https://aws.amazon.com/blogs/aws/now-available-new-c5-instance-sizes-and-bare-metal-instances/
https://aws.amazon.com/blogs/aws/ec2-instance-update-two-more-sizes-of-m5-r5-instances/

### CODE REVIEW

**Comment by djberg96** [comment]
We have GOT to get on v3 so we can do this dynamically...

**Comment by AlexanderZagaynov** [comment]
@djberg96 sorry Dan, I didn't get what do you mean in the context of current PR. 
I understand that `v3` upgrade stuck for awhile, but do you mean we should not update flavors meanwhile?

**Comment by agrare** [comment]
@AlexanderZagaynov I think he means it would be nice to get to v3 so that we don't have to manually update the list in the future

**Comment by agrare** [comment]
Hm travis run is green https://travis-ci.org/ManageIQ/manageiq-providers-amazon/builds/557828866?utm_source=github_status&utm_medium=notification but still says in progress here, merging

**Comment by AlexanderZagaynov** [comment]
@agrare yes, I feel this pain each time I'm making such PRs...

**Pull request merged**
