### PR TITLE
add ca-central region

### PR DESCRIPTION
**Pull request by durandom**
Add Canada (Central) Region

see announcement 
https://aws.amazon.com/about-aws/whats-new/2016/12/announcing-the-aws-canada-central-region/

https://bugzilla.redhat.com/show_bug.cgi?id=1414609

need an darga and euwe bz

### CODE REVIEW

**Comment by durandom** [comment]
@simaishi can you clone the BZ?

**Comment by simaishi** [comment]
@durandom I can clone for z-stream only after the master PR is merged and the BZ goes to POST.

**Comment by Ladas** [comment]
@durandom looks great :+1:

**Comment by simaishi** [comment]
Darga backport details:

```
$ git log -1
commit f20a5943e9b75dfd83719e7d670ff2a4ba66c709
Author: Ladislav Smola <lsmola@redhat.com>
Date:   Wed Jan 25 09:51:51 2017 +0100

    Merge pull request #113 from durandom/ca_central_region
    
    add ca-central region
    (cherry picked from commit 48d7d0af041214b01dc90fd763bfc511279cc1d6)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1416820
```

**Comment by durandom** [comment]
euwe BZ https://bugzilla.redhat.com/show_bug.cgi?id=1416819

**Comment by simaishi** [comment]
Euwe backport details:

```
$ git log -1
commit 7a2933bcd4f6bee37dbd61b13ff1c9dd6114b567
Author: Ladislav Smola <lsmola@redhat.com>
Date:   Wed Jan 25 09:51:51 2017 +0100

    Merge pull request #113 from durandom/ca_central_region
    
    add ca-central region
    (cherry picked from commit 48d7d0af041214b01dc90fd763bfc511279cc1d6)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1416819
```

**Pull request merged**
