### PR TITLE
Add checking on route before retrieving its gateway_id

### PR DESCRIPTION
**Pull request by hsong-rh**
Use safe navigation operator to avoid nil exception.

https://bugzilla.redhat.com/show_bug.cgi?id=1678564

### CODE REVIEW

**Comment by hsong-rh** [comment]
@roliveri Please review.

**Comment by JPrause** [comment]
@hsong-rh if this can be backported, can you add the hammer/yes label.

**Comment by hsong-rh** [comment]
@roliveri Can you add the hammer/yes label? thanks.

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 78413ee5b690cf5230ac2416b85092bc96c443ae
Author: Richard Oliveri <oliveri.richard.github@gmail.com>
Date:   Tue Feb 19 11:27:20 2019 -0500

    Merge pull request #515 from hsong-rh/route_without_gateway_id
    
    Add checking on route before retrieving its gateway_id
    
    (cherry picked from commit 120a5bafb29a2f062bca408b738804a334c43509)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1702069
```

**Pull request merged**
