### PR TITLE
Ensure managers change zone and provider region with cloud manager

### PR DESCRIPTION
**Pull request by Ladas**
Depends on:
- [x] https://github.com/ManageIQ/manageiq/pull/14741

Ensure managers change zone and provider region with cloud manager

Fixes BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1439268

### CODE REVIEW

**Comment by Ladas** [comment]
@miq-bot add_label euwe/yes, fine/yes, bug

**Comment by Ladas** [comment]
@miq-bot assign @agrare

**Comment by bronaghs** [comment]
Wonderful @Ladas 👍

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 0389bc3226d8f9adca5fb944a0d67ad91e5b5f5c
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Wed Apr 12 11:04:51 2017 -0400

    Merge pull request #212 from Ladas/ensure_managers_change_zone_and_provider_region_with_cloud_manager
    
    Ensure managers change zone and provider region with cloud manager
    (cherry picked from commit 544050624aa271596c906e455500c826bbae3260)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1441740
```

**Comment by simaishi** [comment]
Backported what's relevant for Euwe (network manager only, and no EBS/S3). @Ladas please verify.
 
Euwe backport details:

```
$ git log -1
commit 70703d0dc2bfdc73e1f980c0ea64da6cf70e7d11
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Wed Apr 12 11:04:51 2017 -0400

    Merge pull request #212 from Ladas/ensure_managers_change_zone_and_provider_region_with_cloud_manager
    
    Ensure managers change zone and provider region with cloud manager
    (cherry picked from commit 544050624aa271596c906e455500c826bbae3260)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1441742
```

**Pull request merged**
