### PR TITLE
[FINE] Fine tag mapping

### PR DESCRIPTION
**Pull request by juliancheal**
Backport of Tag mapping in Graph refresh

https://github.com/ManageIQ/manageiq-providers-amazon/pull/382

Fixes BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1537111

### CODE REVIEW

**Comment by bronaghs** [comment]
@juliancheal - This depends on changes being made to the manageiq repo - https://github.com/ManageIQ/manageiq/pull/16734
Can that be backported?

See my comment here: https://bugzilla.redhat.com/show_bug.cgi?id=1537111#c3

**Comment by juliancheal** [comment]
> @juliancheal - This depends on changes being made to the manageiq repo - ManageIQ/manageiq#16734
> Can that be backported?

Yeah I need to push my PR up for that, been trying to test it locally.

**Comment by juliancheal** [comment]
@cben does this look correct to you?

**Comment by cben** [comment]
Superficially looks good.
Did you test the UI?  Are @djberg96's model & UI changes to let user define mappings for Images and Vms already present on Fine?

**Comment by juliancheal** [comment]
@cben I did, but I wasn't sure if it was working. I don't know about @djberg96's changes.

**Comment by cben** [comment]
cross-ref: The reason this is still blocked (and Travis failing) is most of the mapping machinery graph refresh additions are not backported to fine yet: https://github.com/ManageIQ/manageiq/pull/17068#issuecomment-373117170

**Comment by juliancheal** [comment]
Decided not to go ahead with backporting tag mapping to Fine.

**Pull request closed without merging**
