### PR TITLE
Removal of static attributes in factories

### PR DESCRIPTION
**Pull request by juliancheal**
FactoryBot 5.0 will remove static attributes, replacing with dynamic

### CODE REVIEW

**Comment by djberg96** [comment]
Does this work with 4 and 5, or just 5?

**Comment by juliancheal** [comment]
@djberg96 they'll be deprecated in 4.11 https://thoughtbot.com/blog/deprecating-static-attributes-in-factory_bot-4-11

**Comment by djberg96** [comment]
@juliancheal Interesting. I wonder how much of a speed/memory increase we'll see in the specs.

**Comment by djberg96** [comment]
Anyway, :+1:

**Comment by juliancheal** [comment]
@miq-bot assign @agrare

can haz merge?

**Pull request merged**
