### PR TITLE
add metal to names and remove dedicated

### PR DESCRIPTION
**Pull request by AlexanderZagaynov**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1724686
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1724631

### CODE REVIEW

**Comment by agrare** [comment]
@AlexanderZagaynov can you look at the spec failures?  Looks like just flavor counts

**Comment by AlexanderZagaynov** [comment]
@agrare I'm on it right now

**Comment by agrare** [comment]
:+1: thanks

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 799ec026e1382b3d0cc78867881afa6836a5e3e4
Author: Adam Grare <agrare@redhat.com>
Date:   Tue Sep 3 15:12:44 2019 -0400

    Merge pull request #554 from AlexanderZagaynov/BZ-1724686_metal_type_names
    
    add metal to names and remove dedicated
    
    (cherry picked from commit caaa4e5eed895184f85c5e551bf3d3a128077477)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1724686
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1724631
```

**Comment by simaishi** [comment]
@AlexanderZagaynov Travis is failing in ivanchuk branch. Please take a look:

https://travis-ci.org/ManageIQ/manageiq-providers-amazon/builds/580706225

**Comment by AlexanderZagaynov** [comment]
@simaishi fix PR: https://github.com/ManageIQ/manageiq-providers-amazon/pull/555

**Comment by AlexanderZagaynov** [comment]
@simaishi https://github.com/ManageIQ/manageiq-providers-amazon/pull/556

**Pull request merged**
