### PR TITLE
new regions and instance types

### PR DESCRIPTION
**Pull request by AlexanderZagaynov**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1705565
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1703474

### CODE REVIEW

**Comment by AlexanderZagaynov** [comment]
I know :) I'm in the middle of fetching more instance types currently.

**Comment by agrare** [comment]
@AlexanderZagaynov @Ladas don't want to disrupt this PR because this is just a normal update, but would like to investigate using the static regions definition in the aws gem instead of keeping our own copy.

Caching `Aws::Partitions.defaults["partitions"].flat_map { |p| p["regions"].keys }` could be a suitible replacement for `YAML.load_file(ManageIQ::Providers::Amazon::Engine.root.join('db/fixtures/aws_regions.yml')).each_value(&:freeze).freeze` and we wouldn't need to update our own copy of a yaml file

**Comment by AlexanderZagaynov** [comment]
@agrare no, it will be depending on the bundled gem version.
And I'm going to use API queries after update to `v3` gem.

**Comment by agrare** [comment]
> no, it will be depending on the bundled gem version (e.g. can be outdated).

Exactly, when we want to update the regions we would just bump the gem version

> And I'm going to use API queries after update to v3 gem.

Even better

**Comment by AlexanderZagaynov** [comment]
> Exactly, when we want to update the regions we would just bump the gem version

currently we use old `v2` version, and it can be theoretically discontinued
P.S. I've checked right now, and your example returns only ordinary regions.

> > And I'm going to use API queries after update to v3 gem.
> Even better

so, that's the solution :)

**Comment by agrare** [comment]
It looks like that work might have stalled?  I don't mind continuing to do this in the interim but the interim is getting pretty long :)

**Comment by AlexanderZagaynov** [comment]
> It looks like that work might have stalled? I don't mind continuing to do this in the interim but the interim is getting pretty long :)

that's another question )))

**Comment by agrare** [comment]
Looking forward to it :+1:

**Comment by Ladas** [comment]
Yeah going forward, we should use flavors info from the API, like we do in the Topological Inventory https://github.com/Ladas/topological_inventory-collector-amazon/blob/f28f7a572cffbe736bf21967f9ea9e6971947560/lib/topological_inventory/amazon/collector/pricing.rb#L21

And regions can be fetched from this API call https://github.com/ManageIQ/topological_inventory-amazon/blob/8912f2954e666222edcc88899e68a703961e312b/lib/topological_inventory/amazon/collector.rb#L69

So lets talk to Loic and just do this :-)

**Comment by AlexanderZagaynov** [comment]
@miq-bot add_label hammer/yes

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 7ff93bc57f16a12310884ca57f213cc66fdd284e
Author: Adam Grare <agrare@redhat.com>
Date:   Thu May 9 21:44:41 2019 -0400

    Merge pull request #532 from AlexanderZagaynov/BZ-1705565_new_regions_and_instance_types
    
    new regions and instance types
    
    (cherry picked from commit 9d1567e0816e583493924a13b4419b109d23d3a9)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1703474
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1728708
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1703461
```

**Pull request merged**
