### PR TITLE
Add CloudWatch events for VM to a timeline

### PR DESCRIPTION
**Pull request by Ladas**
Add CloudWatch events for VM to a timeline

### CODE REVIEW

**Comment by durandom** [comment]
@Ladas @bronaghs  @blomquisg I'm having a hard time extracting all events in settings.yml into the provider repos, because the event names are generic and there is no way to attribute them to a certain provider.
I like how the event are prefixed with `AWS_EC2_` - should'nt we do this with the cloudwatch and other sources as well?

**Comment by bronaghs** [comment]
@durandom - I see what you mean. The thing it, once extracted to each provider repo there is no need for the prefix so it becomes an exercise to help with the extraction process only. Is that right? Or is it helpful in the timelines too?

**Comment by Ladas** [comment]
@durandom @bronaghs make sense, is there still need for the prefix when we have it extracted? The prefix might be needed for other processing though, but all events have prefix except the API based events, so it should be good.

**Comment by durandom** [comment]
yep, you are right. I thought people view events in the timeline across providers, but I think thats not even possible, it's always in the context of an EMS or other object. So, cool and sorry for the confusion 🎊

**Comment by Ladas** [comment]
@durandom in the context of more providers, there is :source attribute on EmsEvent, to distinct a provider.

**Pull request merged**
