### PR TITLE
new AWS EC2 instance types

### PR DESCRIPTION
**Pull request by AlexanderZagaynov**
announces:
- https://aws.amazon.com/about-aws/whats-new/2018/08/introducing-amazon-ec2-t3-instances
- https://aws.amazon.com/about-aws/whats-new/2018/09/amazon-ec2-f1-instances-now-available-in-an-additional-size

8 new types in total

### CODE REVIEW

**Comment by AlexanderZagaynov** [comment]
@Ladas @bronaghs please review

**Comment by simaishi** [comment]
@AlexanderZagaynov Found 2 BZs that go with this PR... please add BZ link to the PR description if there are more.  I assume this can be `hammer/yes`?

**Comment by AlexanderZagaynov** [comment]
@simaishi I see you added BZ links already. I don't think there is more.
@miq-bot add_label hammer/yes

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit e229f18ee1e31119df0e176e9ac7daa20c977cc0
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Thu Oct 4 13:03:02 2018 -0400

    Merge pull request #493 from AlexanderZagaynov/updates/ec2_f1_new_size
    
    new AWS EC2 instance types
    
    (cherry picked from commit a9f1252e2066231233273693c86595b189f87892)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1623094
    https://bugzilla.redhat.com/show_bug.cgi?id=1636182
```

**Pull request merged**
