### PR TITLE
Rename Amazon block storage manager

### PR DESCRIPTION
**Pull request by gberginc**
Based on [this comment](https://github.com/ManageIQ/manageiq-providers-amazon/pull/101#issuecomment-273215389) from @roliveri, this PR replaces the current `BlockStorageManager` with `StorageManager::EBS`. This has two benefits. First, it explicitly names the block storage type, which is Elastic Block Store, and second, it allows for different types of block storage managers to be used by the amazon provider.

Changes were made in the provider itself as well as the inventory targets.

I am also suggesting changes in the cloud manager, i.e. replacing `block_storage_manager` with `ebs_storage_manager`. Please check whether these changes also make sense.

@Ladas @roliveri: please review. As soon as we agree on the structure, I will provide changes for the manageiq repository (automate and ext management system).

Before merging, we should sync to prevent failures in the main repo that occurred with #101 today (for which I apologise).

@miq-bot add_label euwe/no

### CODE REVIEW

**Comment by gberginc** [comment]
@miq-bot assign @Ladas, @roliveri

**Comment by gberginc** [comment]
@roliveri Although you proposed `StorageManager::EBS` I changed it to `StorageManager::Ebs`. While updating automation models I realised I don't know how to actually make it look for `EBS` as it automatically expected `Ebs` in the name.

If there is a solution to this, I can revert to EBS.

Related PRs in the manageiq repository:
 * ext management system spec [WIP]: https://github.com/ManageIQ/manageiq/pull/13549
 * automation models [WIP]: https://github.com/ManageIQ/manageiq/pull/13550
 * refresh workers update: https://github.com/ManageIQ/manageiq/pull/13457

**Comment by roliveri** [comment]
@gberginc @Ladas This looks good to me.
Should I wait for this to be merged before merging https://github.com/ManageIQ/manageiq/pull/13457 - to prevent interim test breakage?

**Comment by gberginc** [comment]
@roliveri I have removed WIP status of the other PRs on manageiq repo (listed below). Before merging this one, I would like to get LGTMs on the other PRs.

I think the order of merges should be:

 * this one: https://github.com/ManageIQ/manageiq-providers-amazon/pull/107
 * ext management system: https://github.com/ManageIQ/manageiq/pull/13549
 * automation: https://github.com/ManageIQ/manageiq/pull/13550
 * refresh worker: https://github.com/ManageIQ/manageiq/pull/13457

**Comment by roliveri** [comment]
@gberginc @Ladas OK. I don't have merge permissions for this repo. So, once it's merged, I'll handle the others in the appropriate order.

**Comment by Ladas** [comment]
@gberginc nice rename :-)

**Comment by Ladas** [comment]
@roliveri merged, you can proceed :-)

**Pull request merged**
