### PR TITLE
[WIP] Update VCR cassettes with EBS parser

### PR DESCRIPTION
**Pull request by gberginc**
This is a temporary PR that is to be used to get the updated VCRs for the EBS storage manager.

@miq-bot add_label wip

### CODE REVIEW

**Comment by gberginc** [comment]
@miq-bot assign @Ladas

**Comment by gberginc** [comment]
@miq-bot add_label wip

**Comment by sergio-ocon** [comment]
Hi @Ladas can we merge this? I think that there are two other PR depending on this.

Thanks,
Sergio

**Comment by gberginc** [comment]
@sergio-ocon I didn't plan to merge this one, because it will break the specs.

I marked it WIP because we discussed with @Ladas it would be best if I try to extend the specs for EBS based on his AWS account. I already have some other tests so that I can work on the provider. Hopefully, I'll then just be able to migrate those specs.

**Comment by Ladas** [comment]
@gberginc also, I am thinking that I will prepare a set of CloudFormation templates, that would deploy all kinds of data combinations we would need to test. Hopefully packed into one big template. With a little script around that, it should be a nice way to turn any AWS account into a VCR env. Also will be easier to get rid of the data after.

Maybe if you would create CloudFormation template for Vms with Volumes, with the combinations you need to test. I could just deploy that in the VCR AWS Account and we would be testing the same data and crosslinks?

**Comment by Ladas** [comment]
:+1: right, I've already sent these

**Pull request closed without merging**
