### PR TITLE
Turn on batch saving by default

### PR DESCRIPTION
**Pull request by Ladas**
Depends on:
- [x] https://github.com/ManageIQ/manageiq-providers-amazon/pull/290

Turn on batch saving by default

### CODE REVIEW

**Comment by Ladas** [comment]
@agrare well it's quicker :-) but yeah, I'd like to have more testing

**Comment by blomquisg** [comment]
@agrare I'll let you make the call.  You know the cost/benefit better than I do.

**Comment by Ladas** [comment]
@agrare we can merge now safely :-) We could backport to g-release

**Comment by agrare** [comment]
Yes now we can merge it @Ladas :)

**Pull request merged**
